urls.py
from django.urls import path
from . import views

app_name = 'newsns'

urlpatterns = [
    path('', views.index, name='index'),
    path('post', views.post, name='post'),
    path('confirm', views.confirm, name='confirm'),
    path('article/', views.redirect_to_index, name='redirect_to_index'),
    path('article/<int:id>', views.article, name='article'),
    path('censored_word_list', views.censored_word_list, name='censored_word_list'),
    path('secret_word_list/<censored_word>', views.secret_word_list, name='secret_word_list'),
    path('post_comment/', views.redirect_to_index, name='redirect_to_index'),
    path('post_comment/<int:id>', views.post_comment, name='post_comment'),
    path('confirm_comment/', views.confirm_comment, name='confirm_comment'),
    path('signup', views.signup, name='signup'),
    path('login', views.login_view, name='login_view'),
    path('logout', views.logout_view, name='logout_view'),
    path('search_articles', views.search_articles, name='search_articles'),
    path('result', views.result, name='result'),
]

templates/newsns/article.html
{% extends 'newsns/layout.html' %}

{% block title %}article{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>article</h1>

{% if article %}
    {{article.posted_date}}<br/>
    {{article.content | linebreaksbr}}<br/>
{% endif %}

<hr>

{% for c in comments %}
    {{c.posted_date}}<br/>
    {{c.content | linebreaksbr}}<br/>
    {% if c.is_article_contributor %}
        記事投稿者<br/>
    {% elif c.first_posted_date != c.posted_date %}
        初回投稿: {{c.first_posted_date}}<br/>
    {% endif %}
{% endfor %}
{% endblock %}

templates/newsns/censored_word_list.html
{% extends 'newsns/layout.html' %}

{% block title %}censored word list{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>censored</h1>

<form action="{% url 'newsns:censored_word_list' %}" method="post">
    {% csrf_token %}
    {{search_form.as_p}}
    <button>search</button>
</form>

<form action="{% url 'newsns:censored_word_list' %}" method="post">
    {% csrf_token %}
    {{register_form.as_p}}
    <button>register</button>
</form>

{% for cw in censored_words %}
    <hr/>
    <p>
        <a href="{% url 'newsns:secret_word_list' cw %}">
            {{cw}}<br/>
        </a>
    </p>
{% endfor %}
{% endblock %}

templates/newsns/confirm.html
{% extends 'newsns/layout.html' %}

{% block title %}confirm{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>confirm</h1>

<form action="{% url 'newsns:confirm' %}" method="post">
    {% csrf_token %}
    {{ forms }}
    <input type="hidden" name="content" value="{{ content }}">
    <button>post</button>
</form>

<form action="{% url 'newsns:confirm' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="notpost" value="notpost">
    <button>don't post</button>
</form>
{% endblock %}

templates/newsns/confirm_comment.html
{% extends 'newsns/layout.html' %}

{% block title %}confirm{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>confirm</h1>

<form action="{% url 'newsns:confirm_comment' %}" method="post">
    {% csrf_token %}
    {{ forms }}
    <input type="hidden" name="content" value="{{ content }}">
    <input type="hidden" name="article_id" value="{{ article.id }}">
    <button>post</button>
</form>

<form action="{% url 'newsns:confirm_comment' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="notpost" value="notpost">
    <button>don't post</button>
</form>
{% endblock %}

templates/newsns/index.html
{% extends 'newsns/layout.html' %}

{% block title %}index{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>newsns</h1>


<p>
    /newsns/signup<br/>
    /newsns/post<br/>
    /newsns/article/&lt;数字&gt;<br/>
    /newsns/post_comment/&lt;数字&gt;<br/>
    /newsns/censored_word_list<br/>
    /newsns/logout<br/>
</p>

{% for a in articles %}
    <hr/>
    <p>
        <a href="{% url 'newsns:article' a.id %}">
            {{a.posted_date}}<br/>
            {{a.content | linebreaksbr}}<br/>
            {{a.id}}<br/>
        </a>
    </p>
{% endfor %}
{% endblock %}

templates/newsns/layout.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body bgcolor="black" text='#ffffff'>
    <span>user ID: <span>{{login_user.id}}</span></span>
    <span><a href="{% url 'newsns:logout_view' %}">lotout</a></span>

    <div>{% block header %}{% endblock %}</div>
    <div>{% block content %}{% endblock %}</div>
</body>
</html>

templates/newsns/login.html
{% extends 'newsns/layout.html' %}

{% block title %}login{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>login</h1>

<form action="{% url 'newsns:login_view' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>login</button>
</form>
{% endblock %}

templates/newsns/post.html
{% extends 'newsns/layout.html' %}

{% block title %}post{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>post</h1>

<form action="{% url 'newsns:post' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button>post</button>
</form>
{% endblock %}

templates/newsns/post_comment.html
{% extends 'newsns/layout.html' %}

{% block title %}post{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>post</h1>

{% if article %}
    {{article.posted_date}}<br/>
    {{article.content | linebreaksbr}}<br/>

    <form action="{% url 'newsns:post_comment' article.id %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button>post</button>
    </form>
{% endif %}

{% endblock %}

templates/newsns/result.html
{% extends 'newsns/layout.html' %}

{% block title %}result{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>result</h1>

<form action="{% url 'newsns:search' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button>search</button>
</form>

<p>{{search_string}}</p>

{% for a in result %}
    <hr/>
    <p>
        <a href="{% url 'newsns:article' a.id %}">
            {{a.posted_date}}<br/>
            {{a.content | linebreaksbr}}<br/>
            {{a.id}}<br/>
        </a>
    </p>
{% endfor %}
{% endblock %}

templates/newsns/search.html
{% extends 'newsns/layout.html' %}

{% block title %}search{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>search</h1>

<form action="{% url 'newsns:search' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button>search</button>
</form>
{% endblock %}

templates/newsns/secret_word_list.html
{% extends 'newsns/layout.html' %}

{% block title %}censored word list{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>secret words</h1>

<form action="{% url 'newsns:secret_word_list' censored_word %}" method="post">
    {% csrf_token %}
    {{search_form.as_p}}
    <button>search</button>
</form>

<form action="{% url 'newsns:secret_word_list' censored_word %}" method="post">
    {% csrf_token %}
    {{register_form.as_p}}
    <button>search</button>
</form>

<p>
    {% for sw in secret_words %}
        <hr/>
        {{sw}}<br/>
    {% endfor %}
</p>
{% endblock %}

templates/newsns/signup.html
{% extends 'newsns/layout.html' %}

{% block title %}signup{% endblock %}

{% block header %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

{% block content %}
<h1>signup</h1>

<form action="{% url 'newsns:signup' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button>login</button>
</form>
{% endblock %}